### ISSUE TITLE
DAC audio is incorrect on master branch

### ISSUE THREAD

**Issue by shayo** [open-ephys/GUI#256] opened 2015-02-25 23:08 UTC
Something doesn't work right with the audio output (via DAC) in the master branch.
It doesn't output the correct channel. Not sure exactly what it does output.
I ran a couple of experiments recently, and it I noticed right away that something is weird....Please check.
It works well in the old spike sorting branch.

**Comment by aacuevas** [comment] 2015-02-25 23:35
Do you mean selecting the output from the FPGA editor, or from somewhere else?

**Comment by shayo** [comment] 2015-02-26 00:39
In SpikeSorter.

On Wed, Feb 25, 2015 at 6:35 PM, Aarón Cuevas López <
notifications@github.com> wrote:

> Do you mean selecting the output from the FPGA editor, or from somewhere
> else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-ephys/GUI/issues/256#issuecomment-76085511>.
>



-- 
Shay Ohayon
HHMI Postdoc Fellow of the Life Sciences Research Foundation
DiCarlo's lab, MIT, 46-6147
+1 617-324-3593

**Comment by aacuevas** [comment] 2015-02-27 17:19
Ok, I know where the problem is. When we switched to the multisample rate architecture we streamlined some code, which in turn broke some other. This will be fixed along with all the other issues with the Rhythm node, I'm working on it right now.

**Comment by jsiegle** [comment] 2022-07-30 20:35
The source code for the Rhythm Plugins (Acquisition Board and Intan RHD USB) now live here: https://github.com/open-ephys-plugins/rhythm-plugins

If you're still experiencing any problems with these plugins, please open a new issue in that repository.

**Closed by jsiegle** 2022-07-30 20:35 UTC
